In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/Premalatha-success/Datasets/main/TaxiFare.csv')

In [7]:
df.sample(3)

,unique_id,amount,date_time_of_pickup,longitude_of_pickup,latitude_of_pickup,longitude_of_dropoff,latitude_of_dropoff,no_of_passenger
23700,34:48.0,9.0,2013-10-14 21:34:48 UTC,-73.982368,40.677273,-74.002753,40.656082,1
29576,54:52.0,14.9,2011-01-01 21:54:52 UTC,-73.951196,40.785868,-74.002864,40.733398,1
5656,34:00.0,17.5,2013-11-15 19:34:00 UTC,-73.965028,40.760102,-74.000938,40.736260,2

#### Function for Calculating the actual and accurate displacement

In [8]:
from math import radians, cos,sin, asin,sqrt

def distance(lon1, lon2, lat1 , lat2):    
    
    lon1 =radians(lon1)
    lon2 =radians(lon2)
    lat1 =radians(lat1)
    lat2 =radians(lat2)
    
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a))
    
    r = 6371
    return(round (c * r, 2))

In [9]:
longour, latour = -73.980658,	40.733873	
bufd = 0.6
r = 6371;pie = 3.142
lonrag = 180*bufd/(pie*r*cos(radians(longour)))
latrag = 180*bufd/(pie*r)

### Function for checking whether a point lyies in the a probabale range or not

In [10]:

def inrange(lon,  lat ,  bufd):
    return (abs(latour - lat)<latrag) and (abs(longour - lon)<lonrag)

In [11]:
d = []; ds = []
for i in range(df.shape[0]):
    k = distance(df['longitude_of_pickup'][i],longour,
                      df['latitude_of_dropoff'][i],
                      latour)
    kk = inrange(df['longitude_of_pickup'][i],
                      df['latitude_of_dropoff'][i],                      
                      bufd)
    d.append([k< bufd, kk]);

In [12]:
print("True Positives:",d.count([True,True]),  "\tValues that are within the radius and within the range. ")
print("Missed Values :",d.count([True,False]), "\tValues that are within the radius but not within the range. ")
print("Extra Values  :",d.count([False,True]), "\tValues that are within the range but not within the range. ")
print("True Negatives:",d.count([False,False]),"\tValues that are neither within the radius nor within the range. ")

True Positives: 1154 	Values that are within the radius and within the range.
Missed Values : 0 	Values that are within the radius but not within the range.
Extra Values  : 2335 	Values that are within the range but not within the range.
True Negatives: 46511 	Values that are neither within the radius nor within the range.

In [13]:
r = 6371
def ranges(longour, latour, bufd):
    lonrag = 180*bufd/(pie*r*cos(radians(longour)))
    latrag = 180*bufd/(pie*r)
    return [longour,latour,str(bufd) + ' km',longour-lonrag,longour+lonrag,latour-latrag,latour+latrag]
ds = []
for i in range(df.shape[0]):
    k = distance(df['longitude_of_pickup'][i],longour,
                      df['latitude_of_dropoff'][i],
                      latour)
    kk = ranges(df['longitude_of_pickup'][i],
                      df['latitude_of_dropoff'][i],bufd)
    
    ds.append(kk)
ds = pd.DataFrame(ds)
ds.columns = ['Longitude','Latitude','Buffer Distance','MinLongitude', 'MaxLongitude', 'MinLatitude','MaxLatitude']

In [14]:
ds.head(51)

,Longitude,Latitude,Buffer Distance,MinLongitude,MaxLongitude,MinLatitude,MaxLatitude
0,-73.844311,40.712278,0.6 km,-73.863701,-73.824921,40.706883,40.717673
1,-74.016048,40.782004,0.6 km,-74.035641,-73.996455,40.776609,40.787399
2,-73.982738,40.750562,0.6 km,-74.002291,-73.963185,40.745167,40.755957
3,-73.987130,40.758092,0.6 km,-74.006688,-73.967572,40.752697,40.763487
4,-73.968095,40.783762,0.6 km,-73.987631,-73.948559,40.778367,40.789157
5,-74.000964,40.758233,0.6 km,-74.020539,-73.981389,40.752838,40.763628
6,-73.980002,40.764842,0.6 km,-73.999552,-73.960452,40.759447,40.770237
7,-73.951300,40.751048,0.6 km,-73.970816,-73.931784,40.745653,40.756443
8,-74.006462,40.731628,0.6 km,-74.026043,-73.986881,40.726233,40.737023
9,-73.980658,40.758138,0.6 km,-74.000209,-73.961107,40.752743,40.763533
10,-73.996335,40.733559,0.6 km,-74.015904,-73.976766,40.728164,40.738954
11,0.000000,0.000000,0.6 km,-0.005395,0.005395,-0.005395,0.005395
12,-73.991601,40.744682,0.6 km,-74.011165,-73.972037,40.739287,40.750077
13,-74.005360,40.710907,0.6 km,-74.024940,-73.985780,40.705512,40.716302
14,-74.001821,40.722788,0.6 km,-74.021397,-73.982245,40.717393,40.728183
15,0.000000,0.000000,0.6 km,-0.005395,0.005395,-0.005395,0.005395
16,-73.986430,40.737075,0.6 km,-74.005988,-73.966872,40.731680,40.742470
17,-73.981060,40.728412,0.6 km,-74.000611,-73.961509,40.723017,40.733807
18,-73.969505,40.783357,0.6 km,-73.989042,-73.949968,40.777962,40.788752
19,-73.979815,40.755481,0.6 km,-73.999365,-73.960265,40.750086,40.760876
20,-73.985382,40.762070,0.6 km,-74.004938,-73.965826,40.756675,40.767465
21,-73.957954,40.758787,0.6 km,-73.977478,-73.938430,40.753392,40.764182
22,-73.991707,40.763671,0.6 km,-74.011271,-73.972143,40.758276,40.769066
23,-74.000632,40.740577,0.6 km,-74.020206,-73.981058,40.735182,40.745972
24,-73.969622,40.759712,0.6 km,-73.989160,-73.950084,40.754317,40.765107
25,-73.991875,40.774323,0.6 km,-74.011439,-73.972311,40.768928,40.779718
26,0.000000,0.000000,0.6 km,-0.005395,0.005395,-0.005395,0.005395
27,-73.988893,40.757857,0.6 km,-74.008453,-73.969333,40.752462,40.763252
28,-73.989258,40.725690,0.6 km,-74.008819,-73.969697,40.720295,40.731085
29,-73.981020,40.730497,0.6 km,-74.000571,-73.961469,40.725102,40.735892
30,-73.976075,40.759285,0.6 km,-73.995620,-73.956530,40.753890,40.764680
31,-74.010483,40.660366,0.6 km,-74.030069,-73.990897,40.654971,40.665761
32,-73.873027,40.769545,0.6 km,-73.892451,-73.853603,40.764150,40.774940
33,-73.976162,40.738323,0.6 km,-73.995707,-73.956617,40.732928,40.743718
34,-73.993717,40.676617,0.6 km,-74.013283,-73.974151,40.671222,40.682012
35,-73.983330,40.847225,0.6 km,-74.002884,-73.963776,40.841830,40.852620
36,-73.990173,40.762829,0.6 km,-74.009735,-73.970611,40.757434,40.768224
37,-73.995199,40.751084,0.6 km,-74.014767,-73.975631,40.745689,40.756479
38,-73.957740,40.758465,0.6 km,-73.977263,-73.938217,40.753070,40.763860
39,-73.972673,40.791367,0.6 km,-73.992214,-73.953132,40.785972,40.796762
40,-73.984267,40.759608,0.6 km,-74.003822,-73.964712,40.754213,40.765003
41,-74.003899,40.765537,0.6 km,-74.023477,-73.984321,40.760142,40.770932
42,-73.978450,40.716502,0.6 km,-73.997998,-73.958902,40.711107,40.721897
43,-73.988558,40.780748,0.6 km,-74.008118,-73.968998,40.775353,40.786143
44,-73.997037,40.735043,0.6 km,-74.016607,-73.977467,40.729648,40.740438
45,-73.971114,40.736613,0.6 km,-73.990653,-73.951575,40.731218,40.742008
46,-73.980822,40.748797,0.6 km,-74.000373,-73.961271,40.743402,40.754192
47,-73.988877,40.760262,0.6 km,-74.008437,-73.969317,40.754867,40.765657
48,-73.986660,40.751702,0.6 km,-74.006218,-73.967102,40.746307,40.757097
49,-73.992253,40.755947,0.6 km,-74.011817,-73.972689,40.750552,40.761342
50,-73.985582,40.760426,0.6 km,-74.005138,-73.966026,40.755031,40.765821

In [15]:
d = pd.DataFrame(d)
d.head(50)

        0      1
0   False  False
1   False  False
2   False  False
3   False  False
4   False  False
5   False  False
6   False  False
7   False  False
8   False  False
9   False  False
10  False   True
11  False  False
12  False  False
13  False  False
14  False  False
15  False  False
16  False   True
17  False  False
18  False  False
19  False  False
20  False  False
21  False  False
22  False  False
23  False  False
24  False  False
25  False  False
26  False  False
27  False  False
28  False  False
29   True   True
30  False  False
31  False  False
32  False  False
33  False   True
34  False  False
35  False  False
36  False  False
37  False  False
38  False  False
39  False  False
40  False  False
41  False  False
42  False  False
43  False  False
44  False   True
45  False   True
46  False  False
47  False  False
48  False  False
49  False  False